ALTER TABLE roads
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE road_segments
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE dependencies
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
