import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import App from '../../App'
import type { Agency, CurrentUser, Role, User } from './types'
const admin: CurrentUser = { id: '10000000-0000-0000-0000-000000000001', fullName: 'Demo Administrator', email: 'admin@demo.civicos', roles: ['ADMIN'], permissions: ['USER_VIEW', 'USER_CREATE', 'USER_UPDATE', 'ROLE_ASSIGN', 'AGENCY_ASSIGN', 'POLICY_VIEW', 'POLICY_MANAGE', 'AUDIT_VIEW'] }
const agency: Agency = { id: '20000000-0000-0000-0000-000000000001', code: 'BBMP', name: 'Demo Municipal Road Authority', type: 'GOVERNMENT', active: true, createdAt: '2026-08-20T00:00:00Z', updatedAt: '2026-08-20T00:00:00Z' }
const role: Role = { id: '30000000-0000-0000-0000-000000000001', code: 'ADMIN', name: 'Administrator', systemRole: true, permissions: admin.permissions }
const governedUser: User = { id: '40000000-0000-0000-0000-000000000001', agencyId: agency.id, agencyName: agency.name, fullName: 'Agency Officer', email: 'officer@demo.civicos', status: 'ACTIVE', roles: ['AGENCY_OFFICER'], createdAt: '2026-08-20T00:00:00Z', updatedAt: '2026-08-20T00:00:00Z' }
afterEach(() => vi.restoreAllMocks())
describe('Phase 18 admin workspace', () => {
  it('requires an Administrator account and states the operational-authority boundary', () => { render(<App pathname="/app/admin/users" accessToken={null} />); expect(screen.getByRole('heading', { name: /administer access without becoming an operational approver/i })).toBeInTheDocument(); expect(screen.getByText(/audit history cannot be edited or deleted/i)).toBeInTheDocument() })
  it('loads users, agencies, and roles in one governance workspace', async () => { mockApi(); render(<App pathname="/app/admin/users" accessToken="admin-token" />); expect(await screen.findByRole('heading', { name: 'Agency Officer' })).toBeInTheDocument(); expect(screen.getByRole('heading', { name: 'Invite user' })).toBeInTheDocument(); expect(screen.getByText('AGENCY_OFFICER')).toBeInTheDocument() })
  it('invites an account without generating or exposing a production password', async () => { const fetchMock = mockApi(); render(<App pathname="/app/admin/users" accessToken="admin-token" />); await screen.findByRole('heading', { name: 'Invite user' }); fireEvent.change(screen.getByLabelText('Full name'), { target: { value: 'New Inspector' } }); fireEvent.change(screen.getByLabelText('Email'), { target: { value: 'new.inspector@demo.civicos' } }); fireEvent.change(screen.getByLabelText('Role'), { target: { value: 'ADMIN' } }); fireEvent.click(screen.getByRole('button', { name: 'Invite user' })); await waitFor(() => expect(fetchMock.mock.calls.some(([input]) => String(input).endsWith('/api/v1/admin/users'))).toBe(true)); const call = fetchMock.mock.calls.find(([input]) => String(input).endsWith('/api/v1/admin/users')); expect(JSON.parse(String(call?.[1]?.body))).toMatchObject({ fullName: 'New Inspector', email: 'new.inspector@demo.civicos', status: 'INVITED', roleCodes: ['ADMIN'] }); expect(await screen.findByText(/no production password was generated or exposed/i)).toBeInTheDocument() })
  it('shows only safe environment-managed configuration values', async () => { mockApi(); render(<App pathname="/app/admin/configuration" accessToken="admin-token" />); expect(await screen.findByText('ENVIRONMENT-managed')).toBeInTheDocument(); expect(screen.getByText(/secrets, jwt keys, database credentials/i)).toBeInTheDocument(); expect(screen.queryByText(/jwt-secret/i)).not.toBeInTheDocument() })
})
function mockApi() { return vi.spyOn(globalThis, 'fetch').mockImplementation((input) => { const url = String(input); if (url.endsWith('/api/v1/auth/me')) return Promise.resolve(json(admin)); if (url.includes('/api/v1/users?')) return Promise.resolve(json(page([governedUser]))); if (url.includes('/api/v1/admin/agencies?')) return Promise.resolve(json(page([agency]))); if (url.endsWith('/api/v1/admin/roles')) return Promise.resolve(json([role])); if (url.endsWith('/api/v1/admin/users')) return Promise.resolve(json({ ...governedUser, fullName: 'New Inspector', status: 'INVITED' })); if (url.endsWith('/api/v1/admin/configuration')) return Promise.resolve(json({ configurationSource: 'ENVIRONMENT', runtimeMutationSupported: false, ai: { enabled: false, provider: 'mock' }, conflict: { repeatDiggingWindowDays: 30 }, sla: { businessZone: 'Asia/Kolkata' }, verification: { requiredEvidenceTypes: ['COMPLETION', 'RESTORATION'] } })); return Promise.reject(new Error(`Unexpected request: ${url}`)) }) }
function page<T>(data: T[]) { return { data, pagination: { page: 0, size: 100, totalElements: data.length, totalPages: 1 }, meta: {} } }
function json(body: unknown) { return new Response(JSON.stringify(body), { status: 200, headers: { 'Content-Type': 'application/json' } }) }
