import { useEffect, useState, type FormEvent } from 'react'
import { EmptyState } from '../../components/feedback/EmptyState'
import { ErrorState } from '../../components/feedback/ErrorState'
import { LoadingState } from '../../components/feedback/LoadingState'
import { StatusIndicator } from '../../components/status/StatusIndicator'
import { Button } from '../../components/ui/Button'
import { inviteUser, listAgencies, listRoles, listUsers, updateUser } from './api'
import type { Agency, Role, User } from './types'

export function AdminUsersPage({ accessToken, permissions }: { accessToken: string; permissions: string[] }) {
  const [data, setData] = useState<{ users: User[]; agencies: Agency[]; roles: Role[] } | null>(null); const [error, setError] = useState<string | null>(null); const [refresh, setRefresh] = useState(0)
  useEffect(() => { let active = true; Promise.all([listUsers(accessToken), listAgencies(accessToken), listRoles(accessToken)]).then(([users, agencies, roles]) => { if (active) setData({ users: users.data, agencies: agencies.data, roles }) }).catch((failure: unknown) => { if (active) setError(failure instanceof Error ? failure.message : 'User governance could not be loaded.') }); return () => { active = false } }, [accessToken, refresh])
  const canInvite = ['USER_CREATE', 'ROLE_ASSIGN', 'AGENCY_ASSIGN'].every((permission) => permissions.includes(permission))
  const canUpdate = ['USER_UPDATE', 'ROLE_ASSIGN', 'AGENCY_ASSIGN'].every((permission) => permissions.includes(permission))
  return <><AdminHeading eyebrow="Identity governance" title="Users" text="Invite synthetic or operational users, assign agency membership and explicit roles, or change account status. Every write is audited." />{error ? <ErrorState title="User governance could not be loaded" description={error} /> : null}{!error && !data ? <LoadingState label="Loading users, agencies, and roles" /> : null}{data ? <div className="admin-split">{canInvite ? <InviteUserForm accessToken={accessToken} agencies={data.agencies} roles={data.roles} onChanged={() => setRefresh((value) => value + 1)} /> : <PermissionPanel text="User creation, role assignment, and agency assignment permissions are required to invite accounts." />}<section className="panel"><div className="panel-header"><h2>Governed accounts</h2><p>{data.users.length} users visible to this administrator.</p></div>{data.users.length ? <div className="admin-list">{data.users.map((user) => <UserCard key={user.id} user={user} accessToken={accessToken} canUpdate={canUpdate} onChanged={() => setRefresh((value) => value + 1)} />)}</div> : <EmptyState title="No users" description="Invited and active accounts will appear here." />}</section></div> : null}</>
}

function InviteUserForm({ accessToken, agencies, roles, onChanged }: { accessToken: string; agencies: Agency[]; roles: Role[]; onChanged: () => void }) {
  const [fullName, setFullName] = useState(''); const [email, setEmail] = useState(''); const [agencyId, setAgencyId] = useState(''); const [roleCode, setRoleCode] = useState(roles[0]?.code ?? ''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<{ text: string; error: boolean } | null>(null)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(null); try { await inviteUser(accessToken, { fullName, email, agencyId: agencyId || null, status: 'INVITED', roleCodes: [roleCode], reason: 'Administrator invited a user with explicit role assignment.' }); setMessage({ text: 'User invited. No production password was generated or exposed.', error: false }); setFullName(''); setEmail(''); onChanged() } catch (failure) { setMessage({ text: failure instanceof Error ? failure.message : 'The user was not created.', error: true }) } finally { setBusy(false) } }
  return <section className="panel"><div className="panel-header"><h2>Invite user</h2><p>New accounts start as Invited and require a separately configured authentication process.</p></div><form className="admin-form" onSubmit={submit}>{message ? <div className={message.error ? 'admin-alert' : 'admin-success'} role={message.error ? 'alert' : 'status'}>{message.text}</div> : null}<label>Full name<input required value={fullName} onChange={(event) => setFullName(event.target.value)} /></label><label>Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>Agency<select value={agencyId} onChange={(event) => setAgencyId(event.target.value)}><option value="">No agency</option>{agencies.map((agency) => <option key={agency.id} value={agency.id}>{agency.code} · {agency.name}</option>)}</select></label><label>Role<select value={roleCode} onChange={(event) => setRoleCode(event.target.value)}>{roles.map((role) => <option key={role.id} value={role.code}>{role.name}</option>)}</select></label><Button disabled={busy || !roleCode}>{busy ? 'Inviting...' : 'Invite user'}</Button></form></section>
}

function UserCard({ user, accessToken, canUpdate, onChanged }: { user: User; accessToken: string; canUpdate: boolean; onChanged: () => void }) {
  const [status, setStatus] = useState(user.status); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null)
  async function save() { setBusy(true); setError(null); try { await updateUser(accessToken, user.id, { fullName: user.fullName, email: user.email, phone: user.phone, agencyId: user.agencyId, status, roleCodes: user.roles, reason: `Administrator changed account status from ${user.status} to ${status}.` }); onChanged() } catch (failure) { setError(failure instanceof Error ? failure.message : 'Account status was not changed.') } finally { setBusy(false) } }
  return <article className="admin-record"><div><p className="eyebrow">{user.agencyName ?? 'CivicOS'}</p><h3>{user.fullName}</h3><p>{user.email}</p><small>{user.roles.join(', ')}</small></div><div className="admin-record-actions"><StatusIndicator label={user.status} tone={user.status === 'ACTIVE' ? 'success' : user.status === 'INVITED' ? 'info' : 'warning'} />{canUpdate ? <><label>Status<select value={status} onChange={(event) => setStatus(event.target.value)}>{['ACTIVE', 'INVITED', 'SUSPENDED', 'DEACTIVATED', 'DISABLED'].map((value) => <option key={value}>{value}</option>)}</select></label><Button variant="secondary" type="button" disabled={busy || status === user.status} onClick={save}>{busy ? 'Saving...' : 'Save status'}</Button></> : null}{error ? <span role="alert" className="admin-inline-error">{error}</span> : null}</div></article>
}

function PermissionPanel({ text }: { text: string }) { return <section className="panel"><div className="panel-header"><h2>Permission required</h2><p>{text}</p></div></section> }

export function AdminHeading({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <header className="admin-page-heading"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p></header> }
